# Build using both 32-bit and 64-bit Windows.
platform:
  - x64
  - x86

# Because of this:
#   https://help.github.com/articles/dealing-with-line-endings/
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - ps: Write-Host "Installing Yarn 1.5.1..."
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/yarnpkg/yarn/releases/download/v1.5.1/yarn-1.5.1.msi', "$env:temp\yarn-1.5.1.msi")
  - ps: cmd /c start /wait msiexec.exe /i $env:temp\yarn-1.5.1.msi /quiet
  - yarn --version
  - yarn


# Cache some dirs for faster build.
cache:
  - "%LOCALAPPDATA%\\Yarn"


# Quiet-ish build.
build:
  verbosity: minimal


# Run build (tests)
build_script:
  - yarn lint
  - yarn docs-prep
  - yarn test-examples
  - yarn nyc-patch
  - yarn nyc --version
  - yarn nyct

# After successful build
on_success:
  - yarn textcov
  - yarn codecov

environment:
  matrix:
  - nodejs_version: 8
